### PR TITLE
CMS paging and image upload bugfix

### PR DESCRIPTION
**Pull request by morgathal**
The CMS browser did not appear to perform any paging when the CMS responded with totalItemCount > items.length.

If a file was uploaded and upon refresh it was not found in the results, nothing would happen. The fix checks the current page of results for the new file and selects it, otherwise defaults to the uploaded file to ensure it will always be available.

### CODE REVIEW

**Comment by mvanbutselaar** [comment]
Thank you for sharing your work with us. We have assigned reviewers.

One thing to note with regards to the CMS connector API, is that only when the `limit` property is set in the request, the response may be paginated. Otherwise both the returned items and totalItemCount, must be (the count of) all available items.

To comply with the specifications, would you be willing to extend this pull request with an optional operation data property (e.g. `pagingLimit`) and let this flow through to the request?

**Comment by morgathal** [comment]
I would be happy to add/use the limit parameter in the connectors, however I could not find any documentation indicating how to define that page size. I did not want to introduce some arbitrary number. Could I be pointed in the direction of how we might set that value upon invocation or the editor or when configuring a build?

**Comment by ThomasBrekelmans** [comment]
Thank you for your pull request! I particularly liked that:
1) you considered the edge case of uploading a new file that is not yet part of the current set of paged responses,
2) you made a separate reusable component to implement the UI in, so it's easily reused across the different browse modals.

You are correct, the CMS browser currently does not implement anything for handling paged responses and Marijn (mvanbutselaar) is also correct in pointing out that we’ve already taken paging into account in our CMS API.

We like your implementation but would like to do some small tweaks to the React patterns used and the chosen UX / visual design.
We also realize that we haven't provided enough documentation on things like UX best practices, code style, naming conventions and PR-specific guidelines such as matching the indentation used by the existing file.

So what we would like to do is create another commit on this version of the CMS browser ourselves, in which we address the things mentioned before. Me and Youri (yourboss on github) will work on this tomorrow when we can. We hope to have an update ready by the end of the day.
In this version, I'll also implement a way to configure the limit somehow. I'll add some background info on how and why I'm going to do this.

Also, we'll continue to work on some of the contributing guidelines I mentioned and hopefully release those somewhere in the coming weeks/months.

FYI, our documentation for the CMS APIs starts here: http://documentation.fontoxml.com/display/FE/CMS+connectors+API
The API documentation of the browse endpoints is here:
http://documentation.fontoxml.com/display/FE/Browse+for+documents+and+assets
The API documentation for the JS that implements this browse endpoint is here:
http://documentation.fontoxml.com/api/latest/standardbrowseconnector-12423059.html
(this is used by the "data provider" in the cms browser code you've modified)

Specifically the limit and offset parameters are intended for adding support for paged requests.

**Comment by ThomasBrekelmans** [comment]
While working on this today, we concluded that we would much rather implement a show more button instead of paging.
The main reason for this is that a selected item on the current page is not present on the next page, which means the preview column would open and close all the time while paging through the results. This makes the modal too busy and confusing for most users in our opinion.
Furthermore, we like the idea of easily scrolling up and down to compare different items, instead of 'refreshing' the items column for each 'page'. Again we believe scrolling to be less confusing/jarring to most users.

So instead we've started working on a load more button.

We are almost done with an initial implementation. When it's finished and reviewed internally, I'll create a new PR for that implementation and will close this PR.

**Comment by ThomasBrekelmans** [comment]
Closing this PR in favor of #3

**Review by ThomasBrekelmans — COMMENTED** [review]
n/a, see above ^

**Comment by DrRataplan** [comment]
Hello @morgathal,

I'm sorry this PR has been open for so long. We have recently decided on a policy for open-sourced example packages like this one. We are always open for bugfixes and clear improvements. For new features though, we would prefer to be more involved in the design process.

Unfortunately, I am going to close this PR.

My apologies.


Martin Middel

**Pull request closed without merging**
